name       : python-pdm-pep517
version    : 1.0.6
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pdm-pep517/pdm-pep517-1.0.6.tar.gz : a4407703d50fa4d671383a354868b05a13060c1bf38264cbb5ddc9a73e4a1dc5
homepage   : https://github.com/pdm-project/pdm-pep517
license    : MIT
component  : programming.python
summary    : PEP 517 support for PDM
description: |
    Yet another PEP 517 backend. This is the backend for PDM projects, while you can also use it alone. It reads the metadata of PEP 621 format and coverts it to Core metadata.
builddeps  :
    - python-build
    - python-installer
build      : |
    %python3_setup
install    : |
    %python3_install
